import sys
import tkinter as tk
from configparser import ConfigParser
from tkinter.messagebox import showerror, showinfo

from log_control import log

parser = ConfigParser()
parser.read('config.ini')

def gui():
    def clearOut():
        home_frame.pack_forget()
        payment_settings_frame.pack_forget()
        advanced_settings_frame.pack_forget()

    def refreshPaymentSettings():
        log('Refrescando configuracion de pago...')
        input_card_number.delete(0, 'end')
        input_card_owner_name.delete(0, 'end')
        input_card_expiration_month.delete(0, 'end')
        input_card_expiration_year.delete(0, 'end')
        input_cvv.delete(0, 'end')
        input_card_owner_run.delete(0, 'end')
        input_card_number.insert(0, parser.get('payment_process', 'card_number'))
        input_card_owner_name.insert(0, parser.get('payment_process', 'card_owner_name'))
        input_card_expiration_month.insert(0, parser.get('payment_process', 'card_expiration_month'))
        input_card_expiration_year.insert(0, parser.get('payment_process', 'card_expiration_year'))
        input_cvv.insert(0, parser.get('payment_process', 'cvv'))
        input_card_owner_run.insert(0, parser.get('payment_process', 'card_owner_run'))

    def refreshAdvancedSettings():
        log('Refrescando configuracion avanzada...')
        input_log_dir.delete(0, 'end')
        input_alarm_filename.delete(0, 'end')
        input_chrome_files_dir_1.delete(0, 'end')
        input_chrome_files_dir_2.delete(0, 'end')
        input_chrome_files_dir_3.delete(0, 'end')
        input_chrome_files_dir_4.delete(0, 'end')
        input_chrome_files_dir_5.delete(0, 'end')
        input_chrome_files_dir_6.delete(0, 'end')
        input_chrome_files_dir_7.delete(0, 'end')
        input_chrome_files_dir_8.delete(0, 'end')
        input_chrome_files_dir_9.delete(0, 'end')
        input_chrome_files_dir_10.delete(0, 'end')
        input_chrome_files_dir_11.delete(0, 'end')
        input_chrome_files_dir_12.delete(0, 'end')
        input_chrome_files_dir_13.delete(0, 'end')
        input_chrome_files_dir_14.delete(0, 'end')
        input_chrome_files_dir_15.delete(0, 'end')
        input_chrome_filename.delete(0, 'end')
        input_chrome_path.delete(0, 'end')
        input_chrome_port_1.delete(0, 'end')
        input_chrome_port_2.delete(0, 'end')
        input_chrome_port_3.delete(0, 'end')
        input_chrome_port_4.delete(0, 'end')
        input_chrome_port_5.delete(0, 'end')
        input_chrome_port_6.delete(0, 'end')
        input_chrome_port_7.delete(0, 'end')
        input_chrome_port_8.delete(0, 'end')
        input_chrome_port_9.delete(0, 'end')
        input_chrome_port_10.delete(0, 'end')
        input_chrome_port_11.delete(0, 'end')
        input_chrome_port_12.delete(0, 'end')
        input_chrome_port_13.delete(0, 'end')
        input_chrome_port_14.delete(0, 'end')
        input_chrome_port_15.delete(0, 'end')
        input_elements_timeout_limit.delete(0, 'end')
        input_window_width.delete(0, 'end')
        input_window_height.delete(0, 'end')
        input_log_dir.insert(0, parser.get('dirs', 'log_dir'))
        input_alarm_filename.insert(0, parser.get('files', 'alarm_filename'))
        input_chrome_files_dir_1.insert(0, parser.get('dirs', 'chrome_files_dir_1'))
        input_chrome_files_dir_2.insert(0, parser.get('dirs', 'chrome_files_dir_2'))
        input_chrome_files_dir_3.insert(0, parser.get('dirs', 'chrome_files_dir_3'))
        input_chrome_files_dir_4.insert(0, parser.get('dirs', 'chrome_files_dir_4'))
        input_chrome_files_dir_5.insert(0, parser.get('dirs', 'chrome_files_dir_5'))
        input_chrome_files_dir_6.insert(0, parser.get('dirs', 'chrome_files_dir_6'))
        input_chrome_files_dir_7.insert(0, parser.get('dirs', 'chrome_files_dir_7'))
        input_chrome_files_dir_8.insert(0, parser.get('dirs', 'chrome_files_dir_8'))
        input_chrome_files_dir_9.insert(0, parser.get('dirs', 'chrome_files_dir_9'))
        input_chrome_files_dir_10.insert(0, parser.get('dirs', 'chrome_files_dir_10'))
        input_chrome_files_dir_11.insert(0, parser.get('dirs', 'chrome_files_dir_11'))
        input_chrome_files_dir_12.insert(0, parser.get('dirs', 'chrome_files_dir_12'))
        input_chrome_files_dir_13.insert(0, parser.get('dirs', 'chrome_files_dir_13'))
        input_chrome_files_dir_14.insert(0, parser.get('dirs', 'chrome_files_dir_14'))
        input_chrome_files_dir_15.insert(0, parser.get('dirs', 'chrome_files_dir_15'))
        input_chrome_filename.insert(0, parser.get('files', 'chrome_filename'))
        input_chrome_path.insert(0, parser.get('paths', 'chrome_path'))
        input_chrome_port_1.insert(0, parser.get('other', 'chrome_port_1'))
        input_chrome_port_2.insert(0, parser.get('other', 'chrome_port_2'))
        input_chrome_port_3.insert(0, parser.get('other', 'chrome_port_3'))
        input_chrome_port_4.insert(0, parser.get('other', 'chrome_port_4'))
        input_chrome_port_5.insert(0, parser.get('other', 'chrome_port_5'))
        input_chrome_port_6.insert(0, parser.get('other', 'chrome_port_6'))
        input_chrome_port_7.insert(0, parser.get('other', 'chrome_port_7'))
        input_chrome_port_8.insert(0, parser.get('other', 'chrome_port_8'))
        input_chrome_port_9.insert(0, parser.get('other', 'chrome_port_9'))
        input_chrome_port_10.insert(0, parser.get('other', 'chrome_port_10'))
        input_chrome_port_11.insert(0, parser.get('other', 'chrome_port_11'))
        input_chrome_port_12.insert(0, parser.get('other', 'chrome_port_12'))
        input_chrome_port_13.insert(0, parser.get('other', 'chrome_port_13'))
        input_chrome_port_14.insert(0, parser.get('other', 'chrome_port_14'))
        input_chrome_port_15.insert(0, parser.get('other', 'chrome_port_15'))
        input_elements_timeout_limit.insert(0, parser.get('other', 'elements_timeout_limit'))
        input_window_width.insert(0, parser.get('other', 'window_width'))
        input_window_height.insert(0, parser.get('other', 'window_height'))

    def setHomeValues():
        log('Cargando datos de home...')
        input_sku_1.insert(0, parser.get('other', 'sku_1'))
        input_sku_2.insert(0, parser.get('other', 'sku_2'))
        input_sku_3.insert(0, parser.get('other', 'sku_3'))
        input_sku_4.insert(0, parser.get('other', 'sku_4'))
        input_sku_5.insert(0, parser.get('other', 'sku_5'))
        input_sku_6.insert(0, parser.get('other', 'sku_6'))
        input_sku_7.insert(0, parser.get('other', 'sku_7'))
        input_sku_8.insert(0, parser.get('other', 'sku_8'))
        input_sku_9.insert(0, parser.get('other', 'sku_9'))
        input_sku_10.insert(0, parser.get('other', 'sku_10'))
        input_sku_11.insert(0, parser.get('other', 'sku_11'))
        input_sku_12.insert(0, parser.get('other', 'sku_12'))
        input_sku_13.insert(0, parser.get('other', 'sku_13'))
        input_sku_14.insert(0, parser.get('other', 'sku_14'))
        input_sku_15.insert(0, parser.get('other', 'sku_15'))

    def onHome():
        log('Cargando ventana principal...')
        root.title('SNKRMON')
        clearOut()
        home_frame.pack()
        lbl_sku_1.place(x=10, y=10)
        lbl_sku_2.place(x=10, y=35)
        lbl_sku_3.place(x=10, y=60)
        lbl_sku_4.place(x=10, y=85)
        lbl_sku_5.place(x=10, y=110)
        lbl_sku_6.place(x=10, y=135)
        lbl_sku_7.place(x=10, y=160)
        lbl_sku_8.place(x=10, y=185)
        lbl_sku_9.place(x=170, y=10)
        lbl_sku_10.place(x=170, y=35)
        lbl_sku_11.place(x=170, y=60)
        lbl_sku_12.place(x=170, y=85)
        lbl_sku_13.place(x=170, y=110)
        lbl_sku_14.place(x=170, y=135)
        lbl_sku_15.place(x=170, y=160)
        lbl_users_quantity.place(x=170, y=185)
        input_sku_1.place(x=100, y=10)
        input_sku_2.place(x=100, y=35)
        input_sku_3.place(x=100, y=60)
        input_sku_4.place(x=100, y=85)
        input_sku_5.place(x=100, y=110)
        input_sku_6.place(x=100, y=135)
        input_sku_7.place(x=100, y=160)
        input_sku_8.place(x=100, y=185)
        input_sku_9.place(x=260, y=10)
        input_sku_10.place(x=260, y=35)
        input_sku_11.place(x=260, y=60)
        input_sku_12.place(x=260, y=85)
        input_sku_13.place(x=260, y=110)
        input_sku_14.place(x=260, y=135)
        input_sku_15.place(x=260, y=160)
        input_users_quantity.place(x=290, y=180)
        btn_start.place(x=170, y=220)

    def onPaymentSettings():
        log('Cargando configuracion de pago...')
        root.title('Configuracion de pago')
        clearOut()
        refreshPaymentSettings()
        payment_settings_frame.pack()
        lbl_card_number.place(x=10, y=10)
        lbl_card_owner_name.place(x=10, y=35)
        lbl_card_expiration_month.place(x=10, y=60)
        lbl_card_expiration_year.place(x=10, y=85)
        lbl_cvv.place(x=10, y=110)
        lbl_card_owner_run.place(x=10, y=135)
        input_card_number.place(x=190, y=10)
        input_card_owner_name.place(x=190, y=35)
        input_card_expiration_month.place(x=190, y=60)
        input_card_expiration_year.place(x=190, y=85)
        input_cvv.place(x=190, y=110)
        input_card_owner_run.place(x=190, y=135)
        btn_save_payment_settings.place(x=190, y=165)

    def onAdvancedSettings():
        log('Cargando configuracion avanzada...')
        root.title('Configuracion avanzada')
        clearOut()
        refreshAdvancedSettings()
        advanced_settings_frame.pack()
        lbl_log_dir.place(x=10, y=10)
        lbl_alarm_filename.place(x=10,y=35)
        lbl_chrome_files_dir_1.place(x=10, y=60)
        lbl_chrome_files_dir_2.place(x=10, y=85)
        lbl_chrome_files_dir_3.place(x=10, y=110)
        lbl_chrome_files_dir_4.place(x=10, y=135)
        lbl_chrome_files_dir_5.place(x=10, y=160)
        lbl_chrome_files_dir_6.place(x=10, y=185)
        lbl_chrome_files_dir_7.place(x=10, y=210)
        lbl_chrome_files_dir_8.place(x=10, y=235)
        lbl_chrome_files_dir_9.place(x=10, y=260)
        lbl_chrome_files_dir_10.place(x=10, y=285)
        lbl_chrome_files_dir_11.place(x=10, y=310)
        lbl_chrome_files_dir_12.place(x=10, y=335)
        lbl_chrome_files_dir_13.place(x=10, y=360)
        lbl_chrome_files_dir_14.place(x=10, y=385)
        lbl_chrome_files_dir_15.place(x=10, y=410)
        lbl_chrome_filename.place(x=10, y=435)
        lbl_chrome_path.place(x=10, y=460)
        lbl_chrome_port_1.place(x=400, y=10)
        lbl_chrome_port_2.place(x=400, y=35)
        lbl_chrome_port_3.place(x=400, y=60)
        lbl_chrome_port_4.place(x=400, y=85)
        lbl_chrome_port_5.place(x=400, y=110)
        lbl_chrome_port_6.place(x=400, y=135)
        lbl_chrome_port_7.place(x=400, y=160)
        lbl_chrome_port_8.place(x=400, y=185)
        lbl_chrome_port_9.place(x=400, y=210)
        lbl_chrome_port_10.place(x=400, y=235)
        lbl_chrome_port_11.place(x=400, y=260)
        lbl_chrome_port_12.place(x=400, y=285)
        lbl_chrome_port_13.place(x=400, y=310)
        lbl_chrome_port_14.place(x=400, y=335)
        lbl_chrome_port_15.place(x=400, y=360)
        lbl_elements_timeout_limit.place(x=400, y=385)
        lbl_window_width.place(x=400, y=410)
        lbl_window_height.place(x=400, y=435)
        input_log_dir.place(x=145, y=10)
        input_alarm_filename.place(x=145, y=35)
        input_chrome_files_dir_1.place(x=145, y=60)
        input_chrome_files_dir_2.place(x=145, y=85)
        input_chrome_files_dir_3.place(x=145, y=110)
        input_chrome_files_dir_4.place(x=145, y=135)
        input_chrome_files_dir_5.place(x=145, y=160)
        input_chrome_files_dir_6.place(x=145, y=185)
        input_chrome_files_dir_7.place(x=145, y=210)
        input_chrome_files_dir_8.place(x=145, y=235)
        input_chrome_files_dir_9.place(x=145, y=260)
        input_chrome_files_dir_10.place(x=145, y=285)
        input_chrome_files_dir_11.place(x=145, y=310)
        input_chrome_files_dir_12.place(x=145, y=335)
        input_chrome_files_dir_13.place(x=145, y=360)
        input_chrome_files_dir_14.place(x=145, y=385)
        input_chrome_files_dir_15.place(x=145, y=410)
        input_chrome_filename.place(x=145, y=435)
        input_chrome_path.place(x=145, y=460)
        input_chrome_port_1.place(x=535, y=10)
        input_chrome_port_2.place(x=535, y=35)
        input_chrome_port_3.place(x=535, y=60)
        input_chrome_port_4.place(x=535, y=85)
        input_chrome_port_5.place(x=535, y=110)
        input_chrome_port_6.place(x=535, y=135)
        input_chrome_port_7.place(x=535, y=160)
        input_chrome_port_8.place(x=535, y=185)
        input_chrome_port_9.place(x=535, y=210)
        input_chrome_port_10.place(x=535, y=235)
        input_chrome_port_11.place(x=535, y=260)
        input_chrome_port_12.place(x=535, y=285)
        input_chrome_port_13.place(x=535, y=310)
        input_chrome_port_14.place(x=535, y=335)
        input_chrome_port_15.place(x=535, y=360)
        input_elements_timeout_limit.place(x=535, y=385)
        input_window_width.place(x=535, y=410)
        input_window_height.place(x=535, y=435)
        btn_save_advanced_settings.place(x=400, y=465)

    def savePaymentSettings():
        log('Guardando configuracion de pago...')
        parser.set('payment_process', 'card_number', card_number.get())
        parser.set('payment_process', 'card_owner_name', card_owner_name.get())
        parser.set('payment_process', 'card_expiration_month', card_expiration_month.get())
        parser.set('payment_process', 'card_expiration_year', card_expiration_year.get())
        parser.set('payment_process', 'cvv', cvv.get())
        parser.set('payment_process', 'card_owner_run', card_owner_run.get())
        # Si el archivo tiene modo escritura, entonces se sobreescribe con la nueva informacion
        with open('config.ini', 'w') as configfile:
            parser.write(configfile)
        showinfo('Configuracion guardada', 'La configuracion de pago se ha guardado correctamente.')
        log('La configuracion de pago se ha guardado correctamente.', 20)
        onHome()

    def saveAdvancedSettings():
        log('Guardando configuracion avanzada...')
        parser.set('dirs', 'log_dir', log_dir.get())
        parser.set('files', 'alarm_filename', alarm_filename.get())
        parser.set('dirs', 'chrome_files_dir_1', chrome_files_dir_1.get())
        parser.set('dirs', 'chrome_files_dir_2', chrome_files_dir_2.get())
        parser.set('dirs', 'chrome_files_dir_3', chrome_files_dir_3.get())
        parser.set('dirs', 'chrome_files_dir_4', chrome_files_dir_4.get())
        parser.set('dirs', 'chrome_files_dir_5', chrome_files_dir_5.get())
        parser.set('dirs', 'chrome_files_dir_6', chrome_files_dir_6.get())
        parser.set('dirs', 'chrome_files_dir_7', chrome_files_dir_7.get())
        parser.set('dirs', 'chrome_files_dir_8', chrome_files_dir_8.get())
        parser.set('dirs', 'chrome_files_dir_9', chrome_files_dir_9.get())
        parser.set('dirs', 'chrome_files_dir_10', chrome_files_dir_10.get())
        parser.set('dirs', 'chrome_files_dir_11', chrome_files_dir_11.get())
        parser.set('dirs', 'chrome_files_dir_12', chrome_files_dir_12.get())
        parser.set('dirs', 'chrome_files_dir_13', chrome_files_dir_13.get())
        parser.set('dirs', 'chrome_files_dir_14', chrome_files_dir_14.get())
        parser.set('dirs', 'chrome_files_dir_15', chrome_files_dir_15.get())
        parser.set('files', 'chrome_filename', chrome_filename.get())
        parser.set('paths', 'chrome_path', chrome_path.get())
        parser.set('other', 'chrome_port_1', chrome_port_1.get())
        parser.set('other', 'chrome_port_2', chrome_port_2.get())
        parser.set('other', 'chrome_port_3', chrome_port_3.get())
        parser.set('other', 'chrome_port_4', chrome_port_4.get())
        parser.set('other', 'chrome_port_5', chrome_port_5.get())
        parser.set('other', 'chrome_port_6', chrome_port_6.get())
        parser.set('other', 'chrome_port_7', chrome_port_7.get())
        parser.set('other', 'chrome_port_8', chrome_port_8.get())
        parser.set('other', 'chrome_port_9', chrome_port_9.get())
        parser.set('other', 'chrome_port_10', chrome_port_10.get())
        parser.set('other', 'chrome_port_11', chrome_port_11.get())
        parser.set('other', 'chrome_port_12', chrome_port_12.get())
        parser.set('other', 'chrome_port_13', chrome_port_13.get())
        parser.set('other', 'chrome_port_14', chrome_port_14.get())
        parser.set('other', 'chrome_port_15', chrome_port_15.get())
        parser.set('other', 'elements_timeout_limit', elements_timeout_limit.get())
        parser.set('other', 'window_width', window_width.get())
        parser.set('other', 'window_height', window_height.get())
        # Si el archivo tiene modo escritura, entonces se sobreescribe con la nueva informacion
        with open('config.ini', 'w') as configfile:
            parser.write(configfile)
        showinfo('Configuracion guardada', 'La configuracion avanzada se ha guardado correctamente.')
        log('La configuracion avanzada se ha guardado correctamente.', 20)
        onHome()

    def start():
        parser.set('other', 'sku_1', sku_1.get())
        parser.set('other', 'sku_2', sku_2.get())
        parser.set('other', 'sku_3', sku_3.get())
        parser.set('other', 'sku_4', sku_4.get())
        parser.set('other', 'sku_5', sku_5.get())
        parser.set('other', 'sku_6', sku_6.get())
        parser.set('other', 'sku_7', sku_7.get())
        parser.set('other', 'sku_8', sku_8.get())
        parser.set('other', 'sku_9', sku_9.get())
        parser.set('other', 'sku_10', sku_10.get())
        parser.set('other', 'sku_11', sku_11.get())
        parser.set('other', 'sku_12', sku_12.get())
        parser.set('other', 'sku_13', sku_13.get())
        parser.set('other', 'sku_14', sku_14.get())
        parser.set('other', 'sku_15', sku_15.get())
        with open('config.ini', 'w') as configfile:
            parser.write(configfile)
        log('Se ha guardado el listado de SKUs.', 20)
        root.destroy()

    log('Configurando GUI...')
    root = tk.Tk()
    root.resizable(False, False)
    root.iconbitmap('icon.ico')

    log('Configurando frames...')
    # Home Frame
    sku_1 = tk.StringVar()
    sku_2 = tk.StringVar()
    sku_3 = tk.StringVar()
    sku_4 = tk.StringVar()
    sku_5 = tk.StringVar()
    sku_6 = tk.StringVar()
    sku_7 = tk.StringVar()
    sku_8 = tk.StringVar()
    sku_9 = tk.StringVar()
    sku_10 = tk.StringVar()
    sku_11 = tk.StringVar()
    sku_12 = tk.StringVar()
    sku_13 = tk.StringVar()
    sku_14 = tk.StringVar()
    sku_15 = tk.StringVar()
    users_quantity = tk.StringVar()
    home_frame = tk.Frame(root, width=350, height=260)
    lbl_sku_1 = tk.Label(home_frame, text='SKU usuario 1: ')
    lbl_sku_2 = tk.Label(home_frame, text='SKU usuario 2: ')
    lbl_sku_3 = tk.Label(home_frame, text='SKU usuario 3: ')
    lbl_sku_4 = tk.Label(home_frame, text='SKU usuario 4: ')
    lbl_sku_5 = tk.Label(home_frame, text='SKU usuario 5: ')
    lbl_sku_6 = tk.Label(home_frame, text='SKU usuario 6: ')
    lbl_sku_7 = tk.Label(home_frame, text='SKU usuario 7: ')
    lbl_sku_8 = tk.Label(home_frame, text='SKU usuario 8: ')
    lbl_sku_9 = tk.Label(home_frame, text='SKU usuario 9: ')
    lbl_sku_10 = tk.Label(home_frame, text='SKU usuario 10: ')
    lbl_sku_11 = tk.Label(home_frame, text='SKU usuario 11: ')
    lbl_sku_12 = tk.Label(home_frame, text='SKU usuario 12: ')
    lbl_sku_13 = tk.Label(home_frame, text='SKU usuario 13: ')
    lbl_sku_14 = tk.Label(home_frame, text='SKU usuario 14: ')
    lbl_sku_15 = tk.Label(home_frame, text='SKU usuario 15: ')
    lbl_users_quantity = tk.Label(home_frame, text='Cantidad de usuarios: ')
    input_sku_1 = tk.Entry(home_frame, width=7, textvariable=sku_1)
    input_sku_2 = tk.Entry(home_frame, width=7, textvariable=sku_2)
    input_sku_3 = tk.Entry(home_frame, width=7, textvariable=sku_3)
    input_sku_4 = tk.Entry(home_frame, width=7, textvariable=sku_4)
    input_sku_5 = tk.Entry(home_frame, width=7, textvariable=sku_5)
    input_sku_6 = tk.Entry(home_frame, width=7, textvariable=sku_6)
    input_sku_7 = tk.Entry(home_frame, width=7, textvariable=sku_7)
    input_sku_8 = tk.Entry(home_frame, width=7, textvariable=sku_8)
    input_sku_9 = tk.Entry(home_frame, width=7, textvariable=sku_9)
    input_sku_10 = tk.Entry(home_frame, width=7, textvariable=sku_10)
    input_sku_11 = tk.Entry(home_frame, width=7, textvariable=sku_11)
    input_sku_12 = tk.Entry(home_frame, width=7, textvariable=sku_12)
    input_sku_13 = tk.Entry(home_frame, width=7, textvariable=sku_13)
    input_sku_14 = tk.Entry(home_frame, width=7, textvariable=sku_14)
    input_sku_15 = tk.Entry(home_frame, width=7, textvariable=sku_15)
    input_users_quantity = tk.OptionMenu(home_frame, users_quantity, *['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15'])
    users_quantity.set('1')
    btn_start = tk.Button(home_frame, text='Comenzar', command=start)
    setHomeValues()

    # Payment Settings Frame
    card_number = tk.StringVar()
    card_owner_name = tk.StringVar()
    card_expiration_month = tk.StringVar()
    card_expiration_year = tk.StringVar()
    cvv = tk.StringVar()
    card_owner_run = tk.StringVar()
    payment_settings_frame = tk.Frame(root, width=400, height=200)
    lbl_card_number = tk.Label(payment_settings_frame, text='Numero de tarjeta: ')
    lbl_card_owner_name = tk.Label(payment_settings_frame, text='Nombre del propietario: ')
    lbl_card_expiration_month = tk.Label(payment_settings_frame, text='Mes de expiracion: ')
    lbl_card_expiration_year = tk.Label(payment_settings_frame, text='Año de expiracion: ')
    lbl_cvv = tk.Label(payment_settings_frame, text='Codigo de seguridad: ')
    lbl_card_owner_run = tk.Label(payment_settings_frame, text='RUN del propietario de la tarjeta: ')
    input_card_number = tk.Entry(payment_settings_frame, width=18, textvariable=card_number)
    input_card_owner_name = tk.Entry(payment_settings_frame, width=32, textvariable=card_owner_name)
    input_card_expiration_month = tk.Entry(payment_settings_frame, width=4, textvariable=card_expiration_month)
    input_card_expiration_year = tk.Entry(payment_settings_frame, width=4, textvariable=card_expiration_year)
    input_cvv = tk.Entry(payment_settings_frame, width=5, textvariable=cvv)
    input_card_owner_run = tk.Entry(payment_settings_frame, width=12, textvariable=card_owner_run)
    btn_save_payment_settings = tk.Button(payment_settings_frame, text='Guardar', command=savePaymentSettings)

    # Advanced Settings Frame
    log_dir = tk.StringVar()
    alarm_filename = tk.StringVar()
    chrome_files_dir_1 = tk.StringVar()
    chrome_files_dir_2 = tk.StringVar()
    chrome_files_dir_3 = tk.StringVar()
    chrome_files_dir_4 = tk.StringVar()
    chrome_files_dir_5 = tk.StringVar()
    chrome_files_dir_6 = tk.StringVar()
    chrome_files_dir_7 = tk.StringVar()
    chrome_files_dir_8 = tk.StringVar()
    chrome_files_dir_9 = tk.StringVar()
    chrome_files_dir_10 = tk.StringVar()
    chrome_files_dir_11 = tk.StringVar()
    chrome_files_dir_12 = tk.StringVar()
    chrome_files_dir_13 = tk.StringVar()
    chrome_files_dir_14 = tk.StringVar()
    chrome_files_dir_15 = tk.StringVar()
    chrome_filename = tk.StringVar()
    chrome_path = tk.StringVar()
    chrome_port_1 = tk.StringVar()
    chrome_port_2 = tk.StringVar()
    chrome_port_3 = tk.StringVar()
    chrome_port_4 = tk.StringVar()
    chrome_port_5 = tk.StringVar()
    chrome_port_6 = tk.StringVar()
    chrome_port_7 = tk.StringVar()
    chrome_port_8 = tk.StringVar()
    chrome_port_9 = tk.StringVar()
    chrome_port_10 = tk.StringVar()
    chrome_port_11 = tk.StringVar()
    chrome_port_12 = tk.StringVar()
    chrome_port_13 = tk.StringVar()
    chrome_port_14 = tk.StringVar()
    chrome_port_15 = tk.StringVar()
    elements_timeout_limit = tk.StringVar()
    window_width = tk.StringVar()
    window_height = tk.StringVar()
    advanced_settings_frame = tk.Frame(root, width=600, height=503)
    lbl_log_dir = tk.Label(advanced_settings_frame, text='Log dir: ')
    lbl_alarm_filename = tk.Label(advanced_settings_frame, text='Alarm filename: ')
    lbl_chrome_files_dir_1 = tk.Label(advanced_settings_frame, text='Chrome files dir 1: ')
    lbl_chrome_files_dir_2 = tk.Label(advanced_settings_frame, text='Chrome files dir 2: ')
    lbl_chrome_files_dir_3 = tk.Label(advanced_settings_frame, text='Chrome files dir 3: ')
    lbl_chrome_files_dir_4 = tk.Label(advanced_settings_frame, text='Chrome files dir 4: ')
    lbl_chrome_files_dir_5 = tk.Label(advanced_settings_frame, text='Chrome files dir 5: ')
    lbl_chrome_files_dir_6 = tk.Label(advanced_settings_frame, text='Chrome files dir 6: ')
    lbl_chrome_files_dir_7 = tk.Label(advanced_settings_frame, text='Chrome files dir 7: ')
    lbl_chrome_files_dir_8 = tk.Label(advanced_settings_frame, text='Chrome files dir 8: ')
    lbl_chrome_files_dir_9 = tk.Label(advanced_settings_frame, text='Chrome files dir 9: ')
    lbl_chrome_files_dir_10 = tk.Label(advanced_settings_frame, text='Chrome files dir 10: ')
    lbl_chrome_files_dir_11 = tk.Label(advanced_settings_frame, text='Chrome files dir 11: ')
    lbl_chrome_files_dir_12 = tk.Label(advanced_settings_frame, text='Chrome files dir 12: ')
    lbl_chrome_files_dir_13 = tk.Label(advanced_settings_frame, text='Chrome files dir 13: ')
    lbl_chrome_files_dir_14 = tk.Label(advanced_settings_frame, text='Chrome files dir 14: ')
    lbl_chrome_files_dir_15 = tk.Label(advanced_settings_frame, text='Chrome files dir 15: ')
    lbl_chrome_filename = tk.Label(advanced_settings_frame, text='Chrome filename: ')
    lbl_chrome_path = tk.Label(advanced_settings_frame, text='Chrome path: ')
    lbl_chrome_port_1 = tk.Label(advanced_settings_frame, text='Chrome port 1: ')
    lbl_chrome_port_2 = tk.Label(advanced_settings_frame, text='Chrome port 2: ')
    lbl_chrome_port_3 = tk.Label(advanced_settings_frame, text='Chrome port 3: ')
    lbl_chrome_port_4 = tk.Label(advanced_settings_frame, text='Chrome port 4: ')
    lbl_chrome_port_5 = tk.Label(advanced_settings_frame, text='Chrome port 5: ')
    lbl_chrome_port_6 = tk.Label(advanced_settings_frame, text='Chrome port 6: ')
    lbl_chrome_port_7 = tk.Label(advanced_settings_frame, text='Chrome port 7: ')
    lbl_chrome_port_8 = tk.Label(advanced_settings_frame, text='Chrome port 8: ')
    lbl_chrome_port_9 = tk.Label(advanced_settings_frame, text='Chrome port 9: ')
    lbl_chrome_port_10 = tk.Label(advanced_settings_frame, text='Chrome port 10: ')
    lbl_chrome_port_11 = tk.Label(advanced_settings_frame, text='Chrome port 11: ')
    lbl_chrome_port_12 = tk.Label(advanced_settings_frame, text='Chrome port 12: ')
    lbl_chrome_port_13 = tk.Label(advanced_settings_frame, text='Chrome port 13: ')
    lbl_chrome_port_14 = tk.Label(advanced_settings_frame, text='Chrome port 14: ')
    lbl_chrome_port_15 = tk.Label(advanced_settings_frame, text='Chrome port 15: ')
    lbl_elements_timeout_limit = tk.Label(advanced_settings_frame, text='Elements timeout limit: ')
    lbl_window_width = tk.Label(advanced_settings_frame, text='Chrome width: ')
    lbl_window_height = tk.Label(advanced_settings_frame, text='Chrome height: ')
    input_log_dir = tk.Entry(advanced_settings_frame, width=7, textvariable=log_dir)
    input_alarm_filename = tk.Entry(advanced_settings_frame, width=11, textvariable=alarm_filename)
    input_chrome_files_dir_1 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_1)
    input_chrome_files_dir_2 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_2)
    input_chrome_files_dir_3 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_3)
    input_chrome_files_dir_4 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_4)
    input_chrome_files_dir_5 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_5)
    input_chrome_files_dir_6 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_6)
    input_chrome_files_dir_7 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_7)
    input_chrome_files_dir_8 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_8)
    input_chrome_files_dir_9 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_9)
    input_chrome_files_dir_10 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_10)
    input_chrome_files_dir_11 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_11)
    input_chrome_files_dir_12 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_12)
    input_chrome_files_dir_13 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_13)
    input_chrome_files_dir_14 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_14)
    input_chrome_files_dir_15 = tk.Entry(advanced_settings_frame, width=20, textvariable=chrome_files_dir_15)
    input_chrome_filename = tk.Entry(advanced_settings_frame, width=12, textvariable=chrome_filename)
    input_chrome_path = tk.Entry(advanced_settings_frame, width=32, textvariable=chrome_path)
    input_chrome_port_1 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_1)
    input_chrome_port_2 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_2)
    input_chrome_port_3 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_3)
    input_chrome_port_4 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_4)
    input_chrome_port_5 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_5)
    input_chrome_port_6 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_6)
    input_chrome_port_7 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_7)
    input_chrome_port_8 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_8)
    input_chrome_port_9 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_9)
    input_chrome_port_10 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_10)
    input_chrome_port_11 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_11)
    input_chrome_port_12 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_12)
    input_chrome_port_13 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_13)
    input_chrome_port_14 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_14)
    input_chrome_port_15 = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port_15)
    input_elements_timeout_limit = tk.Entry(advanced_settings_frame, width=4, textvariable=elements_timeout_limit)
    input_window_width = tk.Entry(advanced_settings_frame, width=6, textvariable=window_width)
    input_window_height = tk.Entry(advanced_settings_frame, width=6, textvariable=window_height)
    btn_save_advanced_settings = tk.Button(advanced_settings_frame, text='Guardar', command=saveAdvancedSettings)

    log('Configurando barra de menu...')
    menu_bar = tk.Menu(root)
    file_menu = tk.Menu(menu_bar, tearoff=False)
    file_menu.add_command(label='Ventana principal', command=onHome)
    file_menu.add_command(label='Salir', command=root.quit)
    config_menu = tk.Menu(menu_bar, tearoff=False)
    config_menu.add_command(label='Datos de pago', command=onPaymentSettings)
    config_menu.add_command(label='Avanzado', command=onAdvancedSettings)
    menu_bar.add_cascade(label='Archivo', menu=file_menu)
    menu_bar.add_cascade(label='Configurar', menu=config_menu)
    root.config(menu=menu_bar)

    onHome()

    def exit():
        log('Cerrando SNKRMON...')
        sys.exit()

    root.protocol('WM_DELETE_WINDOW', exit)
    root.mainloop()

    return { 'users_quantity': int(users_quantity.get()) }
