import sys
from tkinter.messagebox import showerror, showinfo
from log_control import log
import tkinter as tk
from configparser import ConfigParser
import sys

parser = ConfigParser()
parser.read('config.ini')

def gui():
    def clearOut():
        home_frame.pack_forget()
        payment_settings_frame.pack_forget()
        advanced_settings_frame.pack_forget()

    def refreshPaymentSettings():
        log('Refrescando configuracion de pago...')
        input_card_number.delete(0, 'end')
        input_card_owner_name.delete(0, 'end')
        input_card_expiration_month.delete(0, 'end')
        input_card_expiration_year.delete(0, 'end')
        input_cvv.delete(0, 'end')
        input_card_owner_run.delete(0, 'end')
        input_card_number.insert(0, parser.get('payment_process', 'card_number'))
        input_card_owner_name.insert(0, parser.get('payment_process', 'card_owner_name'))
        input_card_expiration_month.insert(0, parser.get('payment_process', 'card_expiration_month'))
        input_card_expiration_year.insert(0, parser.get('payment_process', 'card_expiration_year'))
        input_cvv.insert(0, parser.get('payment_process', 'cvv'))
        input_card_owner_run.insert(0, parser.get('payment_process', 'card_owner_run'))

    def refreshAdvancedSettings():
        log('Refrescando configuracion avanzada...')
        input_log_dir.delete(0, 'end')
        input_alarm_filename.delete(0, 'end')
        input_chrome_files_dir.delete(0, 'end')
        input_chrome_filename.delete(0, 'end')
        input_chrome_path.delete(0, 'end')
        input_chrome_port.delete(0, 'end')
        input_elements_timeout_limit.delete(0, 'end')
        input_window_width.delete(0, 'end')
        input_window_height.delete(0, 'end')
        input_log_dir.insert(0, parser.get('dirs', 'log_dir'))
        input_alarm_filename.insert(0, parser.get('files', 'alarm_filename'))
        input_chrome_files_dir.insert(0, parser.get('dirs', 'chrome_files_dir'))
        input_chrome_filename.insert(0, parser.get('files', 'chrome_filename'))
        input_chrome_path.insert(0, parser.get('paths', 'chrome_path'))
        input_chrome_port.insert(0, parser.get('other', 'chrome_port'))
        input_elements_timeout_limit.insert(0, parser.get('other', 'elements_timeout_limit'))
        input_window_width.insert(0, parser.get('other', 'window_width'))
        input_window_height.insert(0, parser.get('other', 'window_height'))

    def onHome():
        log('Cargando ventana principal...')
        root.title('SNKRMON')
        clearOut()
        home_frame.pack()
        lbl_sku.place(x=80, y=10)
        input_sku.place(x=115, y=10)
        btn_start.place(x=93, y=40)

    def onPaymentSettings():
        log('Cargando configuracion de pago...')
        root.title('Configuracion de pago')
        clearOut()
        refreshPaymentSettings()
        payment_settings_frame.pack()
        lbl_card_number.place(x=10, y=10)
        lbl_card_owner_name.place(x=10, y=35)
        lbl_card_expiration_month.place(x=10, y=60)
        lbl_card_expiration_year.place(x=10, y=85)
        lbl_cvv.place(x=10, y=110)
        lbl_card_owner_run.place(x=10, y=135)
        input_card_number.place(x=190, y=10)
        input_card_owner_name.place(x=190, y=35)
        input_card_expiration_month.place(x=190, y=60)
        input_card_expiration_year.place(x=190, y=85)
        input_cvv.place(x=190, y=110)
        input_card_owner_run.place(x=190, y=135)
        btn_save_payment_settings.place(x=190, y=160)

    def onAdvancedSettings():
        log('Cargando configuracion avanzada...')
        root.title('Configuracion avanzada')
        clearOut()
        refreshAdvancedSettings()
        advanced_settings_frame.pack()
        lbl_log_dir.place(x=10, y=10)
        lbl_alarm_filename.place(x=10,y=35)
        lbl_chrome_files_dir.place(x=10, y=60)
        lbl_chrome_filename.place(x=10, y=85)
        lbl_chrome_path.place(x=10, y=110)
        lbl_chrome_port.place(x=10, y=135)
        lbl_elements_timeout_limit.place(x=10, y=160)
        lbl_window_width.place(x=10, y=185)
        lbl_window_height.place(x=10, y=210)
        input_log_dir.place(x=145, y=10)
        input_alarm_filename.place(x=145, y=35)
        input_chrome_files_dir.place(x=145, y=60)
        input_chrome_filename.place(x=145, y=85)
        input_chrome_path.place(x=145, y=110)
        input_chrome_port.place(x=145, y=135)
        input_elements_timeout_limit.place(x=145, y=160)
        input_window_width.place(x=145, y=185)
        input_window_height.place(x=145, y=210)
        btn_save_advanced_settings.place(x=145, y=235)

    def savePaymentSettings():
        log('Guardando configuracion de pago...')
        parser.set('payment_process', 'card_number', card_number.get())
        parser.set('payment_process', 'card_owner_name', card_owner_name.get())
        parser.set('payment_process', 'card_expiration_month', card_expiration_month.get())
        parser.set('payment_process', 'card_expiration_year', card_expiration_year.get())
        parser.set('payment_process', 'cvv', cvv.get())
        parser.set('payment_process', 'card_owner_run', card_owner_run.get())
        # Si el archivo tiene modo escritura, entonces se sobreescribe con la nueva informacion
        with open('config.ini', 'w') as configfile:
            parser.write(configfile)
        showinfo('Configuracion guardada', 'La configuracion de pago se ha guardado correctamente.')
        log('La configuracion de pago se ha guardado correctamente.', 20)
        onHome()

    def saveAdvancedSettings():
        log('Guardando configuracion avanzada...')
        parser.set('dirs', 'log_dir', log_dir.get())
        parser.set('files', 'alarm_filename', alarm_filename.get())
        parser.set('dirs', 'chrome_files_dir', chrome_files_dir.get())
        parser.set('files', 'chrome_filename', chrome_filename.get())
        parser.set('paths', 'chrome_path', chrome_path.get())
        parser.set('other', 'chrome_port', chrome_port.get())
        parser.set('other', 'elements_timeout_limit', elements_timeout_limit.get())
        parser.set('other', 'window_width', window_width.get())
        parser.set('other', 'window_height', window_height.get())
        # Si el archivo tiene modo escritura, entonces se sobreescribe con la nueva informacion
        with open('config.ini', 'w') as configfile:
            parser.write(configfile)
        showinfo('Configuracion guardada', 'La configuracion avanzada se ha guardado correctamente.')
        log('La configuracion avanzada se ha guardado correctamente.', 20)
        onHome()

    def start():
        if sku.get() == '':
            showerror('Error', 'El SKU no puede estar vacio.')
        else:
            root.destroy()

    log('Configurando GUI...')
    root = tk.Tk()
    root.resizable(False, False)
    root.iconbitmap('icon.ico')

    log('Configurando frames...')
    # Home Frame
    sku = tk.StringVar()
    home_frame = tk.Frame(root, width=250, height=75)
    lbl_sku = tk.Label(home_frame, text='SKU: ')
    input_sku = tk.Entry(home_frame, width=7, textvariable=sku)
    btn_start = tk.Button(home_frame, text='Comenzar', command=start)
    # Payment Settings Frame
    card_number = tk.StringVar()
    card_owner_name = tk.StringVar()
    card_expiration_month = tk.StringVar()
    card_expiration_year = tk.StringVar()
    cvv = tk.StringVar()
    card_owner_run = tk.StringVar()
    payment_settings_frame = tk.Frame(root, width=400, height=200)
    lbl_card_number = tk.Label(payment_settings_frame, text='Numero de tarjeta: ')
    lbl_card_owner_name = tk.Label(payment_settings_frame, text='Nombre del propietario: ')
    lbl_card_expiration_month = tk.Label(payment_settings_frame, text='Mes de expiracion: ')
    lbl_card_expiration_year = tk.Label(payment_settings_frame, text='Año de expiracion: ')
    lbl_cvv = tk.Label(payment_settings_frame, text='Codigo de seguridad: ')
    lbl_card_owner_run = tk.Label(payment_settings_frame, text='RUN del propietario de la tarjeta: ')
    input_card_number = tk.Entry(payment_settings_frame, width=18, textvariable=card_number)
    input_card_owner_name = tk.Entry(payment_settings_frame, width=32, textvariable=card_owner_name)
    input_card_expiration_month = tk.Entry(payment_settings_frame, width=4, textvariable=card_expiration_month)
    input_card_expiration_year = tk.Entry(payment_settings_frame, width=4, textvariable=card_expiration_year)
    input_cvv = tk.Entry(payment_settings_frame, width=5, textvariable=cvv)
    input_card_owner_run = tk.Entry(payment_settings_frame, width=12, textvariable=card_owner_run)
    btn_save_payment_settings = tk.Button(payment_settings_frame, text='Guardar', command=savePaymentSettings)
    # Advanced Settings Frame
    log_dir = tk.StringVar()
    alarm_filename = tk.StringVar()
    chrome_files_dir = tk.StringVar()
    chrome_filename = tk.StringVar()
    chrome_path = tk.StringVar()
    chrome_port = tk.StringVar()
    elements_timeout_limit = tk.StringVar()
    window_width = tk.StringVar()
    window_height = tk.StringVar()
    advanced_settings_frame = tk.Frame(root, width=355, height=275)
    lbl_log_dir = tk.Label(advanced_settings_frame, text='Log dir: ')
    lbl_alarm_filename = tk.Label(advanced_settings_frame, text='Alarm filename: ')
    lbl_chrome_files_dir = tk.Label(advanced_settings_frame, text='Chrome files dir: ')
    lbl_chrome_filename = tk.Label(advanced_settings_frame, text='Chrome filename: ')
    lbl_chrome_path = tk.Label(advanced_settings_frame, text='Chrome path: ')
    lbl_chrome_port = tk.Label(advanced_settings_frame, text='Chrome port: ')
    lbl_elements_timeout_limit = tk.Label(advanced_settings_frame, text='Elements timeout limit: ')
    lbl_window_width = tk.Label(advanced_settings_frame, text='Chrome width: ')
    lbl_window_height = tk.Label(advanced_settings_frame, text='Chrome height: ')
    input_log_dir = tk.Entry(advanced_settings_frame, width=7, textvariable=log_dir)
    input_alarm_filename = tk.Entry(advanced_settings_frame, width=11, textvariable=alarm_filename)
    input_chrome_files_dir = tk.Entry(advanced_settings_frame, width=14, textvariable=chrome_files_dir)
    input_chrome_filename = tk.Entry(advanced_settings_frame, width=12, textvariable=chrome_filename)
    input_chrome_path = tk.Entry(advanced_settings_frame, width=32, textvariable=chrome_path)
    input_chrome_port = tk.Entry(advanced_settings_frame, width=6, textvariable=chrome_port)
    input_elements_timeout_limit = tk.Entry(advanced_settings_frame, width=4, textvariable=elements_timeout_limit)
    input_window_width = tk.Entry(advanced_settings_frame, width=6, textvariable=window_width)
    input_window_height = tk.Entry(advanced_settings_frame, width=6, textvariable=window_height)
    btn_save_advanced_settings = tk.Button(advanced_settings_frame, text='Guardar', command=saveAdvancedSettings)

    log('Configurando barra de menu...')
    menu_bar = tk.Menu(root)
    file_menu = tk.Menu(menu_bar, tearoff=False)
    file_menu.add_command(label='Ventana principal', command=onHome)
    file_menu.add_command(label='Salir', command=root.quit)
    config_menu = tk.Menu(menu_bar, tearoff=False)
    config_menu.add_command(label='Datos de pago', command=onPaymentSettings)
    config_menu.add_command(label='Avanzado', command=onAdvancedSettings)
    menu_bar.add_cascade(label='Archivo', menu=file_menu)
    menu_bar.add_cascade(label='Configurar', menu=config_menu)
    root.config(menu=menu_bar)

    onHome()

    def exit():
        log('Cerrando SNKRMON...')
        sys.exit()

    root.protocol('WM_DELETE_WINDOW', exit)
    root.mainloop()

    return sku.get()
